import torch
from transformers import AutoTokenizer
from utils.Tuning import NTForGMO
from peft import LoraConfig, get_peft_model
import torch.nn.functional as F

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

from pathlib import Path
PROJECT_PATH = Path(__file__).resolve().parents[1]
# Configuration
MODEL_NAME = "InstaDeepAI/nucleotide-transformer-V2-250m-multi-species"
MODEL_PATH = f"{PROJECT_PATH}/result/best_model.pt"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# Charge le tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)

# Recree le modèle et applique LoRA
model = NTForGMO(MODEL_NAME)
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["query", "value"],
    lora_dropout=0.1,
    bias="none",
)
model.encoder = get_peft_model(model.encoder, lora_config)

# Chargement des poids du modèle
checkpoint = torch.load(MODEL_PATH, map_location=DEVICE, weights_only=False)
model.load_state_dict(checkpoint["model_state_dict"])
model.to(DEVICE)
model.eval()

# Inference
GMO_CONFIDENCE_THRESHOLD = 0.60  # taux de confiance pour classer comme GMO

def predict(sequence, chunk_size=512):
    tokens = tokenizer(
        sequence.upper(),
        return_tensors="pt",
        padding="max_length",
        truncation=True,
        max_length=chunk_size
    )
    tokens = {k: v.to(DEVICE) for k, v in tokens.items()}
    
    with torch.no_grad():
        try:
            outputs = model(tokens["input_ids"], tokens["attention_mask"])
            probs = F.softmax(outputs["logits"], dim=1)
            gmo_prob = probs[0, 1].item()
            pred = 1 if gmo_prob >= GMO_CONFIDENCE_THRESHOLD else 0
        except Exception as e:
            print(f"Error during prediction: {e}")
    
    return {
        "label": "GMO" if pred == 1 else "Non-GMO",
        "confidence": probs[0, pred].item(),
        "probs": {"Non-GMO": probs[0, 0].item(), "GMO": probs[0, 1].item()}
    }

def visualize_prediction(result, sequence_preview=50):
    """Create a user-friendly visualization of the prediction."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    
    # --- Left: Probability Bar Chart ---
    ax1 = axes[0]
    labels = ['Non-GMO', 'GMO']
    probs = [result['probs']['Non-GMO'], result['probs']['GMO']]
    colors = ['#2ecc71', '#e74c3c']  # Green, Red
    
    bars = ax1.barh(labels, probs, color=colors, height=0.5)
    ax1.set_xlim(0, 1)
    ax1.set_xlabel('Probability')
    ax1.set_title('Classification Probabilities')
    
    # Add GMO confidence threshold line
    ax1.axvline(x=GMO_CONFIDENCE_THRESHOLD, color='orange', linestyle='--', linewidth=2, 
                label=f'GMO Threshold ({GMO_CONFIDENCE_THRESHOLD*100:.0f}%)')
    ax1.legend(loc='lower right')
    
    # Add percentage labels on bars
    for bar, prob in zip(bars, probs):
        ax1.text(prob + 0.02, bar.get_y() + bar.get_height()/2, 
                f'{prob*100:.1f}%', va='center', fontsize=12, fontweight='bold')
    
    # --- Right: Confidence Gauge ---
    ax2 = axes[1]
    ax2.set_aspect('equal')
    ax2.axis('off')
    # Background circle
    theta = np.linspace(0, np.pi, 100)
    ax2.fill_between(np.cos(theta), np.sin(theta), 0, color='#ecf0f1', alpha=0.5)
    
    # Confidence arc
    confidence = result['confidence']
    conf_theta = np.linspace(0, np.pi * confidence, 100)
    color = '#2ecc71' if result['label'] == 'Non-GMO' else '#e74c3c'
    ax2.fill_between(np.cos(conf_theta), np.sin(conf_theta), 0, color=color, alpha=0.7)
    
    # Prediction label
    ax2.text(0, 0.5, result['label'], ha='center', va='center', 
             fontsize=24, fontweight='bold', color=color)
    ax2.text(0, 0.15, f"Confidence: {confidence*100:.1f}%", 
             ha='center', va='center', fontsize=14)
    ax2.set_title('Prediction Result')
    
    plt.tight_layout()
    plt.savefig('prediction_result.png', dpi=150, bbox_inches='tight')
    plt.show()

def visualize_prediction_simple(result):
    """Simple single-panel visualization."""
    fig, ax = plt.subplots(figsize=(8, 5))
    
    labels = ['Non-GMO', 'GMO']
    probs = [result['probs']['Non-GMO'], result['probs']['GMO']]
    colors = ['#27ae60' if result['label'] == 'Non-GMO' else '#bdc3c7',
              '#c0392b' if result['label'] == 'GMO' else '#bdc3c7']
    
    bars = ax.bar(labels, probs, color=colors, width=0.5, edgecolor='black')
    
    # Highlight winning class
    winning_idx = 1 if result['label'] == 'GMO' else 0
    bars[winning_idx].set_edgecolor('gold')
    bars[winning_idx].set_linewidth(3)
    
    ax.set_ylim(0, 1.15)
    ax.set_ylabel('Probability', fontsize=12)
    ax.set_title(f"Prediction: {result['label']} ({result['confidence']*100:.1f}% confident)", 
                 fontsize=14, fontweight='bold')
    
    # Add value labels
    for bar, prob in zip(bars, probs):
        ax.text(bar.get_x() + bar.get_width()/2, prob + 0.03, 
               f'{prob*100:.1f}%', ha='center', fontsize=14, fontweight='bold')
    
    ax.axhline(y=GMO_CONFIDENCE_THRESHOLD, color='orange', linestyle='--', linewidth=2, 
               label=f'GMO Threshold ({GMO_CONFIDENCE_THRESHOLD*100:.0f}%)')
    ax.legend()
    
    plt.tight_layout()
    plt.savefig('prediction_simple.png', dpi=150)
    plt.show()


DNA_GMO = "TATGGCTAGAGCCAGGCAACCGGCTGAGTATAAAAAACAAGCGCCCACAGCTAACGGATTCACTCTGAGCGCCGTCACACTCACAGCTTGTGCGGGATATCATTTGCCTGAAACCGTTTCCCTTAAAGCGAAAAGCCCCCCACCCAAAGGTAAGGAGACGGAGAAATCCTTATTTATAGATTCTTATTTTAGGATGTTTATTAAGTAAACAACGAGCTGATTTGTTTATTTTATGTAAACATGGATGAATTTATTCACTTTAATGCAAACTGTCGTCGGGGACCACGCGGTTCTTTGTCTTCGCAAGAATTGTATTGATTGTTAAACAGCAGTATCTGTATCTTGTGCTTGGCTTTTTTAAAACGAGGAACGGTTATGACTGCAGACAAGTTCATTAGCGCTGCTGCTGCGATTCACAGGTGCTTTTGGATGGAGCCGGCTTCTAGTAAATGGCGTCCTATGAGTTAATGGTTGCGCTAAAACCGGTGTTTGTCACCGTGTAGTCGTGCACGGCTTTTTTTTTTTTTTTTTTTTTTTTGTAGGATTGTGGTGACACTTGGGATTTGATCCCAGGCAGGATACTTTGAAGCGGGTTTCCGAGTTGAGGCTGTCTGGATCCCGGCTGCTCCCTTTGTGCGCCCGATGCGGCGGGGTGTGACCTACTTTAGCATATTAGCCTAGCCACATCATGCTAGCACGCCCTTTAGATTTGCAGCAGTTGCAGTTTTAAGTCTCTCTCGTTTATCCTGGATACTCCCACACACGCTTTTAAAAGATGAATTACTTTCTTTTATTTAACCTAATCTGGTGTCAGTTTATAAGGCTTGCAGTAAAAAGATAGAAGGACTAGCTTTTCTTTTCTTAAAGGTGATAAACTGATTAATAGCTCAAGTGAATGAATGTCCTGATCTGTTTAGTCTTTTCTTATATGTGACAAAGAAATGAGGAAATTGCAAATCAATCGCCTGATCGTCCACTCCGAGAAAAGGCGTGGCTTTCAGGAAATGGATCACCAGTCAAGCGCTTGTGACCGTTCATGAGTCGGCATAAGTTCATTATGCAACTTCCCTTCTCATAAACTAGCTTCAATATTAAGTAATCGCAGACTTCATCTTTTTTAAACGTCTCGTGGTGTGCAATGAATGAGTGTGCTGCTGCATGACGCAGTGATATTCGCTCAAAGGACTTGGAAGGTTCATAAAAGCGAGCGTGATTAAGCAACAGTGGGAGGGCGCTGGTTGTAACGATAGTAAAACGAAGGGAGTGGTCTGTCGGCTAGTCTGTAATGTGGACTGTTCCTTTTTTTTCTCGCCGTGCGTTGCCGCTCTGGCGTCGCGCCACGCGCCGGTAGCCGCAAAGCTGCTCAAAACCGAACCATGTCCTTATATGGTAATAACAGAACGCAGCGCCACTTCCTTTTGTCTGGCTTACTCGGAATGTGCGGCACGAGCTCCTCCTAGCGGCCGAGCTCGTGAACTTCCGCTAGTTAACAGGAAGTAGAAGCGGAATGGCCGCAGGCTTGAGTGCTAATCTTTTTTTTCTTTATCTTTAACAGTTCAGCCATGGAAGATGAAATCGCCGCACTGGTTGTTGACAACGGATCCGGTATGTGCAAGGCCGGATTCGCCGGAGACGACGCCCCTCGTGCTGTCTTCCCCTCCATCGTCGGTCGCCCCAGGCATCAGGTTAGCGACTGCGCATGTCTACTTTTAATGTTACCTTAAATTGTGACTTATGTCATAAATCAGGCCCTAAATCAAGAAAATTGTTCAACTTAATGATATTAACATTAAGATTTTAGTTCAGCTATCACTTGGCAAACACTTAATGATTTCTTTAAATTTTGTTATTTTTGACTTTTTAACTAAAACTGATCTCCTTGTTCAGGGTGTGATGGTGGGTATGGGTCAGAAAGACAGCTACGTTGGTGATGAGGCCCAGAGCAAGAGAGGTATCCTGACCCTGAAGTACCCCATTGAGCACGGTATTGTGACCAACTGGGATGACATGGAGAAGATCTGGCATCACACCTTCTACAACGAGCTGAGAGTTGCCCCTGAGGAGCATCCCGTCCTGCTCACAGAGGCTCCCCTGAACCCCAAAGCCAACAGGGAGAAGATGACCCAGGTACACACCTTTTTTCCACTTGTAATGTTTGGTTAGACCTCAAAGTGTTTATCTCCTCCCCGGTTTCCTTCTGTTCCATTCTCATTTGCTCCTTCCTTCCCCTCCCTCCTCTCCTCCAGGACCTCTCCTCTATAAGATGATCTATCATCAACAGGTCTCTTGACTGTGTGCCTTACCTGCACTTGTGTCTATTTAGGAGAGCAGTAGCTCTGCACTTTATTAGACATTGACTTACTTGCACAAGTGTGAAGGAATGTTTACTTTCTGCACTTTTATTCTACTAACTTCAATCAGCCTCACTCTAATGCATGTAGTGAGTGCAGTGGTCACAAAGGCTAGACTTGTCTTTTTAATTTTGTAAAGCTAAAATGTGTTCTCCCTCTCCTTACAGATCATGTTCGAGACCTTCAACACCCCCGCCATGTACGTTGCCATCCAGGCTGTGCTGTCCCTGTACGCCTCTGGTCGTACCACTGGTATCGTCATGGACTCCGGTGATGGTGTGACCCACACAGTGCCCATCTACGAGGGTTATGCCCTGCCCCACGCCATCCTGCGTCTGGACCTGGCTGGCCGTGACCTCACAGACTACCTCATGAAGATCCTGACAGAGCGTGGCTACTCCTTCACCACCACAGCCGAGAGGGAAATCGTGCGTGACATCAAGGAGAAGCTGTGCTACGTCGCCCTGGACTTCGAGCAGGAGATGGGCACCGCTGCCTCCTCCTCCTCCCTGGAGAAGAGTTACGAGCTGCCTGACGGACAGGTCATCACCATTGGCAATGAGAGGTTCCGTTGCCCTGAGGCCCTCTTCCAGCCTTCCTTCCTTGGTATGTTCCCAACAGAAATCCACCACTTATTAAATCCTCACATGCAAACTGGGCCCTTATGGCATCCTGCAGTTCCACTTGCTAACTGGTGTCTTGTATCTTCTCAGGTATGGAATCCTGCGGAATCCACGAAACCACCTACAACAGCATCATGAAGTGCGACGTCGACATCCGTAAGGACCTGTACGCCAACACCGTGCTGTCTGGAGGTACCACCATGTACCCTGGCATCGCTGACAGGATGCAGAAGGAGATCACAGCCCTGGCCCCATCCACCATGAAGATCAAGGTGAGCTGACTTGCCTTCTAGTGGCATTCATAAGGGTTCAGTTAATGCACTTTTTTTTTAATTTAATTAAGTATCCCAATGACACTCTGCCTCATTGTCCTGCAGATCATCGCCCCACCTGAGCGTAAATACTCCGTCTGGATCGGAGGCTCCATCCTGGCCTCCCTGTCCACCTTCCAGCAGATGTGGATCAGCAAGCAGGAGTACGATGAGTCCGGCCCCTCCATCGTCCACCGCAAATGCTTCTAAACAGACTGTTCCTTCTCCCCTTCCCCAACCAAACGCCCAACAACTTCAGCTCTGTGCAAAACAACCACACACCACACATTTCTCATACACAACTCAGGCGCAGAGAATAGATGACCAACTCATTGGCATGGCTTCAGTTATTTTTGGCGCTTGACTCAGGATTAAAAAAAAAAACTGGAACGATGAAGGAGACAGTAATGTTTTTGGCTAGGTTTTAAAAAAGACACCCCAGGGTTCTGCAGTCTCATCTGGGGCTTAAAAAAAAATGTACATTTTGTTTTTCTTTAAGTCATTCCAAATGTTTGTTAACTGCATTGTTCAGACACATGATTCCAAATGTTAACTTGCATTGTTCAGATACGTATTTGCCTCTGTGAAGGCTGCCCAGTGGTTGGCGCATACTTAACATGGTTGTAGTATCGCTTGTATGTAAGTTATGTCTGGGTTTTTTGTACTTTCAGCCTTAAAAGAATCTTGGTCCTGTTTAATTTTTGTTTTTGTTATGCAAACCCTCATCCTGACCCCACTTCTCCCCCCACGTTGGGAGGCTTCATCCCTGGGGCGGTGGGGCAAGGGGGTGTCTCGGAATGATGGGGTAAACATGGGGTGCCAGACCGGTGGGGCCAACCTGTACACTGACTAAACAATCCCAATAAAGTGCACATGTGTTCCGAA"
DNA_NO_GMO = "GTCAGAAAAATACCAAAATTTTTCAAATGCAAGCCTTGAACTTGGGACCTCACACACACCTAGAACACTTAACCACTAAAGCTGATACACAGATTTGTCACATTTCCACAAAAGGCAAAATAGAAATTTTGAGGAGTTACAACTTTACCCCTTAAAAGAAAATTTAGGCTTTGAAATTTACCTGATCAGAATAGATGGGGATACTGTTGATGTATCGCATCCTCAGGCTCCCACGTGTCCTCCTCAGTGTTATGATTCCACCATATCACCTTCACTAAAGGGATAGACTTCTTCCGAAGAACCTTTACATTGTAATCCAAAATCTGAACCGTCTCCTCCTCGAAGGTCAAATCTGGGCTAACCTCAATCTCCTATACAAGGACAATATAAGTAGGATCAAAGCGGTAATGCCTCAACATCGAGACACGGAATACTTCATGAATACGGTCCAGCTCTAGAGGTAACTCCAACTGATAAGTGACTGGTCCCACTCGCTTTAGAATTTGGTAAGGCCCAATAAACCTAGGGCTCAATTTGCCCTTGCGACTAAACTTTAGAACCTTCTTCTACCGCGAGACCTTGAGAAATATGAAGTTCCTCCACAGAATACACAATCTCAAGTCTCTTCAAATCTGCATAGAACTTCTGTCTATCAGAAGCCGCCTTCAAACGATCCCTAATAAGTCGAAACTTATCATAAGTCTCAGAGACTAACTCAGGACCTAGAACCCGTCGTTCACCCAATTCAGCCCAACATAGGAGAGTGCAACACTTACGTCCATGCACCAACTGCCTCGAAAATCAATAACACAACTCCTCAACATATCCTCCATTATCTGAATCACCCTCTCATATTGACCATCGATCTGAGGATGAAACACAATACTGAAGTCTAACCTCGAACCTAGAGCCTCATGTAACTTTTTCCAGAATCGAGACGTGAAGCGAGGATCCCTATCAGAAATGATTGAGACTGGTACCCCATGTAGTCTCACTATCTAAAAAATGTCGAGCTTTGCCAACTTCTGAAGAGAATAATCGGTCCTAACCGGAATAAAGTGTGCAGACTTGGTCAATCAATCTACGATGACCCAAATAGAATCCTTCTTAGTGGGTGTCAAGGGCAACCCACAAACGAAGTCCATCGTAACTCGCTCCCACTTTCATAGCGGAATCTTAATCGGCTGTAGCAAACCTAAAGTTAACTGATGCTCAGCCTTAACCTGCTGGCATGTCAGACAACGAGCCACAAAATCAGTAACCTCCCATTTCAATCTCGGCCACTAGTACAGTTCTCGAAGATCTCGGTACATCTTATTTCTACCAGGATGCATGGCATAAGGGCTACTATGCACCTCTCTCAAAATAGACTGCCTCAGATCAATATCATTTGGTACACAAATCTGACCACAGAAACAGAGTACCCCATCGTTATTCAGTCCAAAGTGTGTAGTACTACCACTCTTAACCTGACGAAACCGCAGACCCAATAATCCATCCTCTAATTGCCTATCCAAAATATGTTCTATCCAAGTCAGTTTAACCTGCAGTTCATCTAAAAAACTTCCATCGTCGAACAAACTAAGTTGAGCGAACATCGCTCTGAGATCAATCATCAACGCATTGGCCACCACATTGGCCTTGCCAGGATGGTACTCAATAGTACAGTCATAGTCCTTAAGCAGCTCAATCCATCTATGCTATCTAAGATTCAACTCCTTCTAAGTCAGAAGGTACTTAAGGCGTTTGTTATCATTGTAGATAATGCACTTCTCACCGCACAGATAGTGCCTCCAGATTTTTAAAGTAAAGACTACAGTAGCCAACTCCAAATCATACATCAAATAGTTTACCTCATGCATCTTGAGCTGACGAGATGCATATGCCACCACCTTACCATCCTGCATCAAAACACAACCCAAACTCACATGCGATGCATCACTGTACACTATAAACTCCTTTCCAGATTCAGGCTGTATCAGAACAAAAGCTTGAGTTAGAACAGACTTGAGCTTCTCGAAGCTCTCCTACTGCACATCAATCCAAAAAAAAACACCCTTACGTAGCAGCTTAGTTAAGGGTGCTGCAATCAGTGAGAAAACTTCCACAAGCTATCGATAATAACTTGCCAGTCCCAGAAAACTGCGGATCTCGGACACATTCTTAGGTTGTTTCCAATCAGTACAGCCTCAATCTTTCGAGGATCGACATGAATCCCCTCAGCAGAAACCACGTATCCCAAAAATGTTACCTCTTGTAACCAAAATTCGCACTTGCTAAATTTAGCATAGAGCTGCTTTTCCCTCAAAATCTGGAGAACCACTCTAAGGTGCTCGTCATGCTCATCCTCTGTCTTAGAATAAACCAATATGTTGTCGATGAAAACCACGAAGAATGATCCAGGTAGGTCTGAAATACTCGGTTCATCAGATCCATAAATGCGACTGATGCATTTGTCAACCCAAAAGGCATCACTAGAAACTCGTAATGTCTATAACAAGTCCTAAATGCAGTCTTTTGCACATCCACCTCACTAACCCTCAATTGATGGTACCCTGAACGCAGATCAATCTTGGAGAACATAGAAGCCCCTCGGAACTAATCAAACAGATCATTAATCCTTGGAAGTGGATACTTGTTCTTAATGGTCAGCTTATTCAACTATCGATAATTTATACACATCCTCATGGTCCCATCTTTCTTCTTAACAAACAAAATCAGTGCTCCTCATGGAGACACATGGGGACGAATGAAACCATGATCTAAAAGTTCTTGCAGTTGAGCCTTAAGCTCTGTAAGCTTCTTCATTACCATTCGATAGGGGGTGATAAACACTGGAGCTGTACCAGGAAAAAGCTCAATCCTAAATTTCACTTCCCGATTCAAAGGTAAACCCGACAGCTCAGGAAAGACGTCAAAAAGTCCCTTACAGTTTGGATGTCCTTTAAACAGAGTCCCCAGAAATGAAAACACTAAAATAGGCCAAGAACGCCTCACATAATTTATGAACCAGTTTCTCAGCCACCAGTGGAGAGATCACATTATTCAAATAATTCTAACATTATCCAATCAAGACTACCTCATTATCTTCCTCAGTTCTCTAGATGGTCCTCTTAGTTGCACAATCCAGACTGACATGGTGCTTGACCAGCTAGTCCATACCCAGAATCAAGTCAAACACCCCAAACGGAAGCTTTATCAGATTAGCCAGAAATACCGACCCTTGAACCTCTAGCAGAACATCACTATACAGTTTGCTAACTCGAACTGACTGCCCCAGTGGACTTAGTACAATCACCTCACTAGAAATACTCTCAACTAGAATCCCCAAGTTTCCAGATACAGTGCTAGTTAAATAGGAATGTGTGGAACCTATGTCTGCCAAAGCAAAATAAAGTACATCATAAATTAAGAACGTACCGGTAATAATGTCTAAAGCATCTCTATCTTCTCAACGACGAGCAGCATAAACCAGAGCAAGCTGCCTCGCCTCAATCTGTCCAGCACCTCTGCCTAGTGCTCTCTATCTACGACACATACCATTACCACCCCTAGCCTGACCACGGCCCCTTAGTGGCTGCTGAACCACCCTCTGTGGCTACGCAATACTAGAGCTCGCATCTGATCGGCCTTTAGCGGACACTCCCGAATGCGGTACTCCAATGACCCACACCTCAAACATGCCCTGGTCCTCCTCTAACACTCGCCCTGATGGTGTCTACCATAATCTCCACATAGCTACAATCCAGTATGAGCAACAAAGGGCCCAGCTCTAACTGACCCATCAGTCCTGGCCTTTTTCTTAGACCTATATACCGAACTCGAAGGCTCCGAATCCCTCTTGTTCTTACCTCTTTCATGCTCCCTATTTTGGTACTCAGCGCGCTTAACCTTCTCAGCGATCTTCGCATTCTCTACCAAGACAAAAAACTCTTACTCCCTCTATGGAGGTATCAGTACCCTTAAATTATCCCTAAGACCGTCCTCAAAATGGACACACCTCTCATACTCAAACACCACCATACCTCGCACATAATGGCCCACTCTCAGGAATTCGGCCTCATACTCAGCCGCAGATCGATCTCCCTGAGTAAGGTTCAAAAAATCACGCCTACGAGCATTAATGTAACTTGCTCCCACATACTTCCCTTAGAAGGTAGACTTAAAGAACTCTCAAGACAGACGATTGGGCTGTATGCCCTCTTTAACCATCAGTCACCACTGATAGGCCTCATCGCAAAACAACGAGACTACACCCTTCAATTTCTGCTTAGGGGTACAGTCCAAGTCATCTATTATCCTCTAGCCTCCATCCAGCACCTAGCCACATTAGGGGTAACTCCAGTCACACCCCTAAAAAGTTCAGTCCATTGGACTGGAGTTGTTCCGTAACCAACCTTCGGCCCTCAGATCTAGTACTGGGCCTAGCAACCCTCTTTAGTATCCTTAACATAGCCTGGGACAATGCGTCGCCCCCAGCCATATGATCCTGAGACCTAGTCTTAGTAGCAGGTGACATCGGCGTCTCACTCGTATCTAAGTTTGGCATGCTGCCCAAAGAAGAAGACTCAGCCCGAGCCCCTCTACGGCCTCTACCTCAGCCTTTAGCACTACGTCCGCGGATACCTCGTGCACTCATGTCTATTCGAATTTATCTGTATTACGAATTTTATGAATCAATTACAGTTCCAGTATTTATTAACAAATCTTTTATGTAAAGTAGTATCATAAGTTTAGAGTTTGTTTTTCCCAGGGACAGTCTTTATCAGTTTCAGTTTAACTATAGTTTAAATATACACTAACTAAAGTGTTTTCAGAATAGGCTATTTATAATAGTTTACCAGAATACTTACAAGATTGACGCCGAAGACTCAGTGTACCACATTCTCAGTCAAATCATTTCATATCATCTGAAAATTAGTTATTTAAAAACCAAGTTTTAAAACCCAAAATCCACAGTCGAGTTTTACAACCTAGCTCTGATACCACTAAATGTAACACCCCAAACTCGGCCTAGACATTATGGTCGAATCTAACGATGTCACATGAATTGGAGTTTGAAATCAACCGTATCAACTTAACACTGTTTCCGTTTGTTAGCTTTATTTATCTTTCGTCACTTTCAAAACTATTTTCTCGTTAACTGATTTGTTTAAAAACATATTTGGTAGGGGAAGCTTTTAAAACCGTGATAATTAAAAAAAATCATTTGCTTTTAGGAAAACGTCATGAAAATGTCATTTTGAATTAAATTGAGCTTTTTTTGAGTTTACAGTTTAAAAATCCATGAAAATAGTGAAAATCCAAAGTAAAAGCAACAGTCCCAAAAGTCCAATTTACATAAAAATAACCCCAAAAATTAGGAAATAAATACCATAACTGATATTAAAATAGTTCAATAACCATGTGGTCACTGTCGAATCCTCCACCGTACCGATCCATCTAAGTTTGGGGATTACCTGGACACATAAAATAGAACGGGGGTGAGTTTACATAAACTCAGTGTGTAACCCCATAAAAGACATGCATACAATCAATCACAACAAACAATCAAAAGCAAGTCGGGGCCTAATCCCATTTCAGTTTCTGTATCAGATATGTATTAGGGTTTAAGCCCATTGAGTAATAGTATCAGATATACCTTAAGCAGTAAATAGAGTCCTACCCAACCAGCCTCTACACACCATCTCCATCCATTCCTACGTTTCATGTGGGATATAAAACACCCACCCATCCCTACACTCCAAGTAATACTGAATACGGTACATTATTAGTAAATTACAGCTGAGCTACTAGATAATAGGCTTAAAAGCCTTTCAGTACACTTCCTCCAAATATCAACATCCTAACTCGTGCAATACAACATATAGTATATGACATGCTAATACATGAATATCAGTTATACGTACAGTTCATGCATTTAAGGGTTTAAGTAGTGTTTATCGACCCTACGGTAGGTTCAGGGTCAGCTTGGGCAACCCGTGCAACCTTAGAACACATTTCAGTTAAATAGGCTCACATGCCCATGTGGCCTGCCCGTGTGGCCAATACGACCCAATTTGGCCTTGGCTGTGTGGATCATACGGCTTGGCCCAGAATCCTACATGCCAGTGTGGACTACTCGTGTGAACCCACACATTCGTATGGCCCACACGACCCAAATCAGTCTAGCCTGTGTGTCGCACACGGCCTACCTAGCCATCACACGGTAGCATCTTACATGCACGGCCTGGCCTCGTCAATCACTCGCCCATGTTATGGGACATGGCCTGCCACACGCCCATGTGGCATCGATAATGAGGTTTTTGGTTTTCATCGAAACCCTATTTTTTATATTTTTGAGTGCACACACATAGTTCATTTTCGATGTTGAACTCTTTTAAGATCACTAGAACCCTAACACCACGAATCAATTGACTACAAAATAGCACAAGGAGAGCCTTGATCCTCATGATATGATGTGGAACGTATGACGACAATCGAACTAAGGAAGGCGAATGTGATATTCAACAAAAGAAACGAAAACAAAGAGAAAATGGAAGAAAAAAGCCATTAAAGAACACCAAGCATTTAGCTGACATATCCTAGTCAATGTAAGTGCAATTTCTGTTCAGTTTTTAATGATTTTTATGTTTTTGGAGTCGTTGTAGCTTAATCTAGCTAGCCTGAGAACTAATTTGCAAAATTTTTAAAAGTATATCGTTATACCATGAATTTATATTAGTTTTTTTATATTTTATGGATGAAAATGGATGTTGATGATAATTAAACAACTTTTGTAAAGGAAATTTTGATAAATTTGTCAACTAGGGATTAAATTGAAAAATAGAAAAGTATTCATGGTGCATTTGTGAAAAATATGAAATGTAAGGCTTTCTAAGGACCTAAGTAAAATTCGGCTAGCTTGGGTTGGTACTAAATTGCATGAATTTTCATTTTTACGAGCTAGGGACTAAATTGTAATGAATTCAAACTTTTAGGGGCAAAAGTATAATTTTGACAAAATATGATTTTTGGATGAAATTGAATAGAATGAAATTTGAATGAGTTGAATTTGATTATTTAGATCAAGAAAAGCGTCGTACAGATTTAGATTAGGGAAAGAAAAAAGTTTTAGATTAGTTAATCATAACTTCTATTTTGCGATCGAGGTTGTACCTTTAATTAGCACTTTAGTATATTTTAATGAATTCTATTATGCCGTATTGTTGTATTATGTCTTTACGAAAATATCCAACAAAGTTTCGGTGGCTTTCGAATCTCGTTTTAACCTTAGGAATATATAGGATACAAATGACATGTCATTAGGGGTTACCATGTTTTGGGTGCTGGTCCTGTATGTCCTACTGGTGGCTGAGTTTCTGGCATGTGTTTCGGTTACTTGACAGCTTGTGTGAGTAGCACTGTATAGCTATGTCTTGACTAAAAGCTTGTGTGAGCAGCACCGTGTAGCTACGTCTTGACTGACAGCTTGTGTGAGTAGCACCGTGTAGCTACATCTTGACTGGCAACTTGTGTGAGAAGACCTATTATGGCTCGAGACAAAATTTTTCAAAACTTAAACATTTTTCAAAGTTGTACAGGTCACACGCCTATGTGAACAAGCCATGTGCCTCACACAGCTTTAGACACACCCGTGTGTCTAGGCTATGGCAAAACAGGGTATACATACTGACTTGTCCACACGGCCACATGACACGCCTGTGTGCCAAGCCATGGTCGAAACTATATTAGGTCACACGGCTAACCACATGCCCATGTGTCTAGCCTGTGTACCCTTCAAAATGGCCACACACGCCCATGTACCAAGGCTGTGTGCCTCATACGGCCACCAGACACACTCGTGTGTCTAGGCTGTGCTCGAGACTGACTTGATTAACTAAATTACAGCAGACACACGATCAAGACACACATCCGTGTGCTCAACCGTGTGGGGTGAAATTAGGCTTGGTTTAAGCCACATTTCCCACCTATCTCAAGCACTCCAAAACCACCACATTTTAGTATTATTCGCATACATTCATAGGCAACCAAATCAAACATATGTTTCATACCATTCAAATACCATCCAAATCCACTACTCAATTTCACAACCAAGATACCAAATCAATGTATCAAAATCATCACAACTTACATAAGTTCCAAATACATAAACTCATCACTTTATCACATAACTTACCAATTCAACATTCCATATTCAAACCATCACATGAACATTATATACATCATATGACTTACCTATCAAACACATCATTTTGGCCAACTTAAAAGGCCATACATACCAACATTTATAAGCCAAATCTCATGGCTAGATATTCACATCACAAAACATATTAAAATACTTCTAGCCTACACATGCCATATACCATATATACAACTCTCAAAATGGTACCAAAATAGATGTTCGATAGTGTGAATGAAATGCTGACGATTCCCAAATCTGAGCTAGCTTTATAACACTGTAAAACAGAGAACATCTCACACAATAAGCTTTAAAGCTTAGTAAGTTCATGATATAACATATTAAACTCATCAATTAAAATATAATTCTATAAATTAGCAAACTCTTAATGCAACTCATCTCATCCTTCATTTACATAACCTTTCATTTACTTCATACTCAATATCATCAACCACATAGGTTCCGTACATACTTGTATCATCACATTCTATTCTATCACATTTATCACTTCAATGCTCGATGTACTACTTCATTCGATCATAGTTGAACATTCAATAAACTCGCACACTTAGTGCCAATTAATTAGCTGAAACTATAATAATATTGCACACTTAGTGCCATTTCATTAAACCGAACTTATATCGGTATCGCACACTTAGTGACATTTATTCAGCTATCATTGTTATATTCTCGCACACTCAGTGCCATTTTTAATAGCCGTAGCTATTTCATTTCTCGCATACTTAGTGCCTCAAATTCAATTCACATTTCACATACTCCAACTTCTCAATCTCATTTCTATTTATTTCATCACATACAAACATTATACAAACAATATGTATTATATACGAACTTACCTCAGACGTAAATACAACGATATTAGTCGATCAATCGAGTACTTTGTTTTTGCCTCGATCTAGGTTCGAATTTCTCCTTTCTTGATCTATATGTCTTCAAAATTCATTCATTTAAACACCAACACATTCAATTTAATACACAAACACATATATGGGCATTTTTTCACTTTAGCCCTAAAATTGTACATTTTGACATTTTAGTCCTTATTACACAAAACACCAAAATACAAAATTCATCAAAACCATGCCGTAGTTGAATTTTCCTATGATCCCTATCAGCCCATATTTACCATTTATTTCACATTTCAACACCTCGATTTACACTTTTTACAATTTAACCCATTTTACTCAATTTCATCAAAAATTCAAAGACAAAACATGTTAACTCAATACATACCTTTCATTTATTAACATCAAAATTCATAAAACTCATAATTTCATCAATGAATCAACTCAAAATCATTAACAATTTTAGAAATTCAAACATGGGCTTTGTCGAAACCATTCTTTTGAAAACGGGGATCGACTTTGTTAGAAAGTGAAAATTAAAACGGGAGTCGCCACCAATCTTTTATCAGGTGTGATCGGATCACCTTTGTTTTAATAAAACATTTTAGTTTACTAAAACAGGGCCTTTGGTCTACGAAACTTGAGAGGATGAGTTCGGGAGTCGGTTACGTGCGAGGAAAGATTAGCACCCTCGACACGTCCAAAAAAATTGGTACCGAATTGATTAGTTATTGTCTTAATGTCGAAAATTAAGAATCGGGAAGGGACTTGAAATATGATCTTTTCTATTAATACTGATTTTAAAATTCTTGAATTAGCTTAAATCGATTTGTTTAAAGATTTCCTTATCTCGAGATGTCTGAGTATCACATCCCTTAAGTTAGGACACAATACCATGAATTCCCGAGCACAAGGTCGTCTTTTAATTTAAATTGGAAATCCGTGTATTTCAAAACTCAAAAGGATATTTAGCTATTTAAAACCAACGAGAGAACCGAAACCCCGTAAGTTAGGGCACAATTCTTCGATGTTCCAAAATGCGAAACATTGCCTTATTTATTGAAATTAATTAAAACATGAGAAAAATATTCCTAAAGTGAGAAATTAAAAATAGATAAACGACGCAAAAAATGATATCATTAATGAAAAATATTAACATGGAATACTAGAATATTAGAATAACAATAACAATGATATTTACAAAAAAAGAAAATAAAAACAAATCATGTACTAATAATAAAATAGGAAAAATGATATATTTGGTAATAATAATATAAAATAATAATATGTGCATAAAAATACATATATATATGTGCATATAATAAAAGTATGTAATAATAATAGTAATAATATCTACAATAAAAGAAAATATTAGGAAACGTACATAAAAATATATACATAAAAAATTACAACAATAATATAAAATAATGATATGTACAAATATATATATGTACATAAAATATACACTAATGTAATAATAATTATAATAATACTAGCAATAGTAATAATTAGTAATAATAATATATACACAATATGGTATTTAAAATATATATATGTATATATAATAATATTTAAGAATATATACATAAGATGATATAAAATACATACATGGAATAGTATAAGAAATATATAACTAATGCATTAAAAAATATATACATAATATATATAAATACATATAATATATATATACGTATTAGAAATGATAAAATTATTAACACACTACATAAGTAAATAAAATATAATAATAATACTAAAATAATTAATTTAAATAGTAAAATAACTAAAAAGGATTAAATTGAACTAAAAACAAAATATTTGGGGCAAAATTGAAATAAAAATAAAAGGAAAGGACTATATTGAACACGCGCGGAAACAGTGGGGGGCCAAAACAGAAAATATTCCTTCCCATCAAAACTCAGCACATTAGCGGGGACTAAATTGAAAATCACGACAAATTTCGGGGCCCAATTAAAAAAACGAATAATGACTTAATTGCAAAGCAATAAAGAGCGGAAGGGCTAAAAGCGAATTAGCCCTTGCTTTAAAAAAACACGCGGATCCTAGGCGGGTCGGGTCGGGTCGAACCGATCCAAGTTAAAACGACGTCATTTTGGGGTTTAATGGCCAACCCCTAAATGACGTCGTTTTGGGGGGCTATAAAAAGCCCTTTTTCTTCAAAAAAAAATTCATTATTGCACTTGAAAAGGAAAAAAAAGAGAGGGAGAGGGGTGAGGTGATTTCTGGCCACAAGACCGGTCACCATCCGGTCACCGGACCGCCGCCGGCTGCCACCGCCGGCCACCGTGGACGGTGGCCGGAAAAGGTAAAAAAAAATTATTTTTTTTATAATATATATATGTATATGTATATAAAAAGAAAGAAAAGAAAAAAAACAAAAAGAAAGAAAAAAGATTCGACAGAAAAGAAAAAAGAAAAAAAGATACAAACCTTTTTATTGATTTTCTTTTGTATTCAAATTTTGGAGGGATTTTTGTGCTTGTCTTTTTTTCAATCCTCTAAAAAAAACCCCCCCTTACATGATTTTTGAATGGCTTTTTATAGCCATCTTTTACATGATTTTCTATTATTTCTTTTTCTATTTCTTTTGTAGGTGATGGTGGCAGACAATGGATATCAAAAATGGGAGGAAAAAGGGGCAAGTGGGAAAGTGGCTAGGTGGCTAGGGTTTCTTGGTTTTTTTGGGGTTAGGTTTTTTTTTGGGTTTAATGGGCTTTTGAATTGGGTTTAATATTTGGATTTTGTAATGGGTTTGGGTAGATGTAAATGGGTCATGGGTTAAGGGTTTTAGTGGGTTTAGAGGTTTGGTTGGTTTTTGATGTAATCGGGCCTGGGCAATTTGGGCTTCTACAGTTGCCTCTCTTTGCTCATTGTCGTGCAACGGGAATAGAGTAAAGACTTTCAAGGAAGACCAAATTTGCCCGGTCTTGCTAGGTCTTGACTTGCTTTGGAACTCTTCTTGTTTAGTTAGTCCCTTTTCAGTCCACCGCATCTTGTAGCTTTGGTTCACCCCACTGCATTTTATGATATACGCCTTGTAGCTTCAATCTATTCCAATGTAACTTCAAGGATATGAAATTTATGGCTTCGATCTACTTCACTGTAACTTCAGAAATGTGAGATCTACAACTTCAATCTGCTCTTCTATCGCTTCAGTGAGATAAGGTTTGGGGTCTTTTCTTCTGCGACTTCAGAAAGGCAAGCTCTGATGTCCTCGATCAACTCCACTGCAACTTTAAAGAGACAGAATCTGACGTCTTCAATCAGCTTCAATCTTTATTCTCTACTCAGCATGTGATCCTCTCGTAATATGAGTTGATTTTTGAAACTTATCTTGAAAAGCAGATTTTGAAAATACCTCGACATGTGACTCGAGGCTCAACTCACCTCTCGTAGAAATAAAAAACTCAACTCACCTCTCGCAATATGAGTTGATTTTTTTGAAAAATATAAATTGAAAAAATACCTCAGTGTGTGATCTGAAGCTCAACTCACCTCTCGCAATATGAGTTGATTTTTTGAAAGACAGAAATTGAAAATAGCTCAACGCGTGAGCCAAGGCTCAACTCACCTCTCGCAATATGAGTCGATTTTTTTTTGAAAGGCAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCACAATATGAGTTGAATTTTTTTGAAAGACAGAAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATGAGTTGATTTTTGAAAATAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTGAAAATAGAAATAGAAATCACCTCAGCGTGTCCCGAGCCTCAACTCACCTCTCGCAATATGAGTTGATTTTTTTTTTGAAAAACAAAAATTAAAAATACCTCAGCATGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCATGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAATTTACCTCAACCTGTCTTGAGGCTCAATTCATTTCTCGCAATATGAGTTGAATTTTTTTTTGAAAGACAGAAATTGAAAATACCTCAGCAAGTGAACCGAGGTTCAACTCACCTCTCACAATATGAGTTGATTTTTGAAAACAGAAATTCAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCGAAGCGTGTCCTGAGGCTCAACTCACCTCTCGCAATATGAGTTGATTTTTTTTTTAAAACAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACATAAATTGAAATTACCTCAAAGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTGGAATTTTGAAAACAAAATTGAAAATACCTCAATATGTCTTGAGGCTCAACTCATTTCTCGTAATATTAGTTGAATTTTGAAAATAGAAATTGAAATTACCTCAGCGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCACCTCATTTCTCGCAATATGAGTTGAATTTTTTTTTGAAAGACAGAAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATAAGTTGATTTTTGAACACAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCATGTCCCAAGGCTCAACACACCTCTCGAAATATGAGTTGAATTTTGAAAACAGAGATTGAAATTACCTCAGCGTGTCCCGAGGCTCAACTCACCGCTCGCAATATGAGTTGATTTTTTTTTTAAAAACAGAAATTTAAAATACCTCAGCATATCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAAAAATTGAAATTACCTCAACCTGTCTTAAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCATGTCCCGAGGCTCAACTCACCTCTTGCAATATGAGTTGATTTTTTTTTGAAAAACAGAAATTAAAAATACCTCCGCATGTCTTGAGGCTTAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCGTGTCTTGAGGCTCAACTCATTTCTCGCAATATTAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCCTGAGCCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCACAATATGAGTTGAATTTTTTTTTGAAAGACAGAAATTGAAAATATCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATGAGTTTATTTTCGAAAACAGAAATAGAAAATACCTCAACGTGTCTTTAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTTATTGAAAGACAGAAATTTAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTTTCGCAATATAAGTTGATTTTTGAAAACAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTGAAAACATAAATTGAAATTACCTCAGCGTGTCCCGAGGCTCAACTCACCTCTTGCAATATGAGTTGATTTTTAAAAAAAAACAAAAATTAAAAATACCTCAGCAAGTCTTGAGGCTTAACTCATTTCTCGGAATATGAGTTGATTTTTTTTTGAAAAATGAAATTGAAAATACCTAAGCATGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGATCAACTCATTTCTCGCAATATGAGTTGAATTTTTTTTGAAAGACAGGAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATAAGTTGATTTTTGAAAACAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCGTTTCTCGTAATATGAGTTAAATTTTTTTTAAAAGACAGAAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATGAGTTGATTTTTGAAAATAGAAATTGAATATACCTTAACGTGTCTTGAGGCTAAACTCATTTCTCGTAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCGAAGCGTGTCCCGATGCTCAACTCACTTCTCGCAATATGAGTTGATTTTTTTTAAGAACAGAAATTGAAAATACCTCAGCATGTCTTGAGGCTCAACTCATTTCTCATAATATGAGTTGAATTTTGAAAACAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTATGAAAACAGAAATTGAAATTATCTCAGCGTGTCCCGAGGCTCAACTCACATCTCGCAATATGACTTGAATTTGCAAACAGAAAATGAAATTACCTCAGCGTGTCCGAGGCTCAACTCACCTCTTGCAATATGAGTTGATTTTTTTTAAAAAAAGCAAAAATTGAAAATACCTCAGCATGTCTTGAGGCTTAACTCATTTCTCGCAATATGAGTTGAATTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTGAAAACAGAAATTAAAATTAGCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTTAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCGTGTCCCAAGGCTCAACACACCTCTCGAAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCGTGTCCGATGCTCAACTCACCTCTCGCAATATGAGTTGATTTTTTTTGAAAAACAGAAATTGAAAATACCTCAGCATATCTTGATGCTCAGCTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAAATCATTTCTTGCAATATGAGTTGAAGTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGATCAACTCATTTCTCGCAATATGAGTTGACTTTTTTTTTGAAAGATAGAAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATGAGTTGATTTTTAAAAACAAAAATTGAAAATACCTCAACGTGTCTTTTGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTTTTTCAAAGATAGAAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATGAGTTGATTTTCGAAAATAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTATCGTAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCGAAACGTGTCCCGAGGCTCAACGCACCTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCGTGTCTCGAGGCTCAACTCACCTCTCGGAATATGAGTTGATTTTTTTTTTGAAAAATTGAAATTGAAAATACCTAAGCATGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTCAAAACAGAAATTGAAATTACCTCTACGTGTCTTGAGGCTCAACTCATTTGTCGCAATATGAGTTGAATTTTTTTTGAAAGACAGAAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATGAGTTGATTTTGAAAAGAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTGAAAGCATAAATAGAAATTACCTCAGCGTGTCCCGAGGCTCAACTCACCTCTTGCAATATGAGTTGAATTTTAAAAAAAAAACAAAAATTGAAAATACCTCAGCATGTCTTGAGGCTTAACTCATTTCTCGCAATATGAGTTGAATTTTGAAGACAGAAATTGAAATTACCTCAACCTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATAAGTTGATTTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTGAAAACAGAAATTAAAATTAGCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCGTGTCCCAAGGCTCAACACACCTCTCGAAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCGTGTCCCGATGCTCAACTCACCTCTCGCAATATGAGTTGATTTTTTTTTGAAAAACAGAAATTGAAAATACCTCAGCATATCTTGATGCTCAGCTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAAATCATTTCTTGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGATCAACTCATTTCTCGCAATATGAGTTGACTTTTTTTTGAAAGACGGAAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATAAGTTGATTTTGAAAATAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCACAATATGAGTTGAATTTTTTTTGAAAGACAGAAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATGAGTTGATTTTTGAAAAGAGAAATAGAAAATACCTCAACGTGTCTTGAGGCTCAACTCGTTTCTCGTAATATGAGTTGAATTTTTATTGAAAGACAGAAATTAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTTTCGCAATATAAGTTGATTTTGAAAACAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTGAAAACATAAATTCAAATTACCTCAGCGTGTCCCGAGGCTCAACTCACCTCTTGCAATATGAGTTGATTTTTTTTAAAAAAACAAAAATTAAAATACCTCAACAAGTCTTGAGGCTTAACTCTTTCTCGCAATATGAGTTGAATTTTGAAGACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTTTTGAAAGACAGGAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATAAGTTGATTTTTGAAAACAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCGTTTCTCGTAATATGAGTTAATTTTTTTAAAAGACAGAAATTGAAAATACCTCAGCATGTGACCGAGGCTCAACTCACCTCTCGCAATATGAGTTGATTTTTGAAAATAGAAATTGAATATACCTTAACGTGTCAGGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCGAAGCGTGTCCGATGCTCAACTCACTTCTCGCAATATGAGTTGATTTTTTTTTTTGAAGAACAGAAATTGAAAATACCTCAGCATGTCTTGAGGCTCAACTCATTTCTCATAATATGAGTTGAATTTTCAAAACAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTATGAAAACAGAAATTGAAATTATCTCAGCGTGTCCGAGGCTCAACTCACATCTCGCAATATGAATTGAATTTTGAAAACAGAAATTGAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTTAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCGTGTCCCAAGGCTCAACACACCTCTCGAAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCGTGTCCCGATGCTCAACTCACCTCTCGCAATATGAGTTGATTTTTTTTTAGAAAACAGAAATTGAAAATACCTCAGCATATCTTGATGCTCAGCTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAATCATTTCTTGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGATCAACTCATTTCTCGCAATATGAGTTGACTTTTTTTTGAAAGATAGAAATTGAAAATACCTCAGCATGTGAACCGGGCTCAACTCACCTCTCGCAATATGAGTTGATTTTTAAAAACAAAAATTGAAAATACCTCAACGTGTCTTTGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTTTTTCAAAGATAGAAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATGAGTTGATTTTCGAAAACAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTATCGTAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCGAACGTGTCCGAGGCTCAACGCACCTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCGTGTCTCGAGGCTCAACTCACCTCTCGAATATGAGTTGATTTTTTTTGAAAATGAAATTGAAAATACCTAAGCATGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTAAAACAGAAATTGAAATTACCTCTACGTGTCTTGAGGCTCAACTCATTTGTCACAATATGAGTTGAATTTTTTTTGAAAGACAGAAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATGAGTTGATTTTTGAAAAGAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATAGTTGAATTTTGAAAGCATAAATTGAAATTACCTCAGCGTGTCCCGAGGCTCAACTCACCTCTTGCAATATGAGTTGATTTTTAAAAAAAAACAAAAATTGAAAATACCTCAGCATGTCTTGAGGCTTAACTCATTTCTCGCAATATGAGTTGAATTTTGAAGACAGAAATTGAAATTACCTCAACTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTTGAAAGACAGAAATTGAAAATACCTCAGCATGTGACGAGCTCAACTCACTCTCGCAATATAAGTTATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTATATGAGTTGAATTTTGAAAAAAAAAAAAATAATTTTAATATTTATAGAAATTTGAAAACAGAAATTGAAATACCTAGTGTGAGGCTCAACTCATCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATACCTCAAGTGTCTTGAGGCTCAACTCATTTCTCGAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCGTGTCCATGCTCAACCATTCTCGAATATGAGTTGAATTTTGAAAACAGAATTGAAATTACCTCAGCGTGTCCGACTCAACTCATCTCGCAATATGAGTTGATTTTTTGAAAACAGAAATTGAAATACTCAGCATATCTTGATGCTCAGCTCATTTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAATTACCTCAACGTGTCTTGAGGCTCAATCATTTCTTGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGATCAACTCATTTCTCGCAATATGAGTTGACTTTTTTTTTGAAAGATAGAAATTGAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCATATGAGTTGATTTTTAAAACAAAACTGAAAATACTCAACGTGTCTTTGGCTCAACTCATTTCTCGTAATATGAGTTGAATTTTTTTCAAGATAGAAATTGAAAATACCTCAGCATGTGACGAGCTCAACTCACCTCTCGCAATATGGTTGATTTCGAAAACAGAATTGAAATACCTCAACGTGTCTGAGGCTCAACTCATTTATCGTAATATGAGTTGAATTTTGAAACAGAAATTGAAATTACGAAACGTGTCCGAGGCTCAACGCACCTCTCGCAATATGAGTTGAATTTTGAAAACAGAAATTGAAATTACCTCAGCGTGTCTCGAGGCTCAACTCACCTCTCGGAATATGAGTTGATTTTTTTTTTGAAAAATTGAAATTGAAAATACCTAAGCATGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTCAAAACAGAAATTGAAATTACCTCTACGTGTCTTGAGGCTCAACTCATTTGTCGCAATATGAGTTGAATTTTTTTTGAAAGACAGAAATTGAAAATACCTCAGCATGTGAACCGAGGCTCAACTCACCTCTCGCAATATGAGTTGATTTTTGAAAGAGAAATTGAAAATACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATCAGTTGAATTTTGAAAGCATAAATTGAAATTACCTCAGCGTGTCCGAGGCTCAACTCACCTCTTGCAATATGAGTTGATTTTTTTTAAAAAAACAAAAATTGAAAAATACCTCAGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGAAAGAGAAATTGAAAATTACCTCAGCGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTTGAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGCAATATGAGTTGAATTTTGTTTTGAAAACAGAAATTGAAAATACCTCAGCATGTGAGGCTCAACTCACCTCTCGCAATATGAGTTGATTTTGAAAAACAGAAATTGAAATTACCTCAACGTGTCTTGAGGCTCAACTCATTTCTCGTAATATGAGTT"

def visualize_with_sequence(result, sequence, model, tokenizer, chunk_size=512, top_k_regions=5):
    """Visualize prediction with sequence attention highlights."""
    fig = plt.figure(figsize=(14, 8))
    
    # Tokenize and get attention
    tokens = tokenizer(
        sequence.upper(),
        return_tensors="pt",
        padding="max_length",
        truncation=True,
        max_length=chunk_size
    )
    tokens = {k: v.to(DEVICE) for k, v in tokens.items()}
    
    # Get attention weights from encoder
    with torch.no_grad():
        # Access the base model through LoRA wrapper
        encoder_outputs = model.encoder(
            input_ids=tokens["input_ids"],
            attention_mask=tokens["attention_mask"],
            output_attentions=True
        )
        
        # Last layer attention, average over heads
        # Shape: (batch, heads, seq_len, seq_len) -> (seq_len,)
        attention = encoder_outputs.attentions[-1]  # Last layer
        attention = attention.mean(dim=1).squeeze()  # Average heads
        
        # CLS token attention to all other tokens (importance scores)
        cls_attention = attention[0, :].cpu().numpy()  # CLS attends to others
        
        # Also get column-wise attention (how much each position is attended to)
        importance = attention.sum(dim=0).cpu().numpy()
    
    # --- Top subplot: Attention heatmap ---
    ax1 = fig.add_subplot(3, 1, 1)
    
    # Trim to actual sequence length (remove padding)
    seq_len = min(len(sequence), chunk_size)
    importance = importance[:seq_len]
    
    # Normalize importance
    importance = (importance - importance.min()) / (importance.max() - importance.min() + 1e-8)
    
    # Create heatmap
    ax1.imshow([importance], aspect='auto', cmap='YlOrRd', interpolation='nearest')
    ax1.set_yticks([])
    ax1.set_xlabel('Position dans la sequence')
    ax1.set_title("Carte d'importance de l'attention (Rouge = Attention eleve)")
    
    # Add colorbar
    cbar = plt.colorbar(ax1.images[0], ax=ax1, orientation='vertical', fraction=0.02)
    cbar.set_label('Importance')
    
    # --- Middle subplot: Top important regions ---
    ax2 = fig.add_subplot(3, 1, 2)
    
    # Find top-k regions with highest attention
    window_size = 50  # Look at windows of 50bp
    region_scores = []
    for i in range(0, len(importance) - window_size, window_size // 2):
        score = importance[i:i+window_size].mean()
        region_scores.append((i, i + window_size, score))
    
    # Sort by score and get top regions
    region_scores.sort(key=lambda x: x[2], reverse=True)
    top_regions = region_scores[:top_k_regions]
    
    # Display top regions
    ax2.axis('off')
    region_text = "Regions les plus importantes:\n\n"
    for idx, (start, end, score) in enumerate(top_regions, 1):
        region_seq = sequence[start:end].upper()
        region_text += f"{idx}. Position {start}-{end} (score: {score:.3f})\n"
        region_text += f"   {region_seq[:30]}{'...' if len(region_seq) > 30 else ''}\n\n"
    
    ax2.text(0.05, 0.95, region_text, transform=ax2.transAxes, fontsize=10,
             verticalalignment='top', fontfamily='monospace',
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    ax2.set_title("Regions ayant le plus d'attention (Marqueurs de potentiel OGM)")
    
    # --- Bottom subplot: Prediction result ---
    ax3 = fig.add_subplot(3, 1, 3)
    
    labels = ['Non-GMO', 'GMO']
    probs = [result['probs']['Non-GMO'], result['probs']['GMO']]
    colors = ['#27ae60', '#c0392b']
    
    bars = ax3.barh(labels, probs, color=colors, height=0.4)
    ax3.set_xlim(0, 1.1)
    ax3.set_xlabel('Probability')
    
    # Add GMO confidence threshold line
    ax3.axvline(x=GMO_CONFIDENCE_THRESHOLD, color='orange', linestyle='--', linewidth=2,
                label=f'GMO Threshold ({GMO_CONFIDENCE_THRESHOLD*100:.0f}%)')
    ax3.legend(loc='lower right')
    
    for bar, prob in zip(bars, probs):
        ax3.text(prob + 0.02, bar.get_y() + bar.get_height()/2,
                f'{prob*100:.1f}%', va='center', fontsize=12, fontweight='bold')
    
    # Highlight predicted class
    pred_idx = 1 if result['label'] == 'GMO' else 0
    bars[pred_idx].set_edgecolor('gold')
    bars[pred_idx].set_linewidth(3)
    
    ax3.set_title(f"Prediction: {result['label']} (Confidence: {result['confidence']*100:.1f}%)",
                  fontweight='bold')
    
    plt.tight_layout()
    plt.savefig('prediction_with_sequence.png', dpi=150, bbox_inches='tight')
    plt.show()
    
    return top_regions


# Usage in main:
if __name__ == "__main__":
    MAX_LENGTH = 1024
    seq = DNA_NO_GMO
    result = predict(seq, MAX_LENGTH)
    
    # Show with sequence attention
    top_regions = visualize_with_sequence(result, seq, model, tokenizer, MAX_LENGTH)
    
    # Print the important regions
    print("\n=== Potential GMO regions ===")
    for start, end, score in top_regions:
        print(f"Position {start}-{end}: {seq[start:end][:50]}...")